### ISSUE TITLE
Create Test Plan: Batch Account Update Transaction Feature

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#485]
Create a test plan for the feature.
```[tasklist]
### Tasks
- [x] Add test: Account ID field can take a range
- [x] Add test: Account ID can take a list
- [x] Add test: Account ID can take a list and range
- [x] Test the transaction with multiple account ID input values can create all the corresponding transactions
- [x] Test the application throws a user error if the inputs for the account ID list is invalid
- [x] Add test: All account update transaction in the list are created when export is selected by the user
- [x] Add test: The correct file is generated when the transactions are exported
- [x] Add test: The file can be viewed in the batch account update transaction task in the home screen
- [x] Add test: Users can sign the batch account update transaction
- [x] Add test: The batch account update transaction can be collated by the CLI tool
- [x] Add test: The batch account update transaction can be submitted successfully to the network after collation
- [x] Add test: Test many account update transactions can be executed without transactions expiring
```
