### ISSUE TITLE
Transaction Tool v3

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#489]
### Problem

We are redesigning the Transaction Tool application from scratch a a fresh approach in mind. This issue is an epic level issue to track the tasks required to complete the first release of the new application.

Terminology:
v1: This was a version of the Transaction Tool that used Hedera internal Java SDK
v2: This was a version of the Transaction Tool that was updated to use the public Hedera Java SDK
v3: This is the third iteration of the Transaction Tool application that will be tracked here

### Solution

Document the required tasks to complete the project.

```[tasklist]
### Tasks
- [ ] Design the application
- [ ] https://github.com/hashgraph/hedera-transaction-tool-demo/issues/492
- [ ] Design the Postgres database
- [ ] Identify user stories to include in the first release
- [ ] Define releases
- [ ] Create mockups for UI/UX
- [ ] Document user stories
- [ ] Implement the database
- [ ] Implement mockups for UI/UX
- [ ] Implement tests
- [ ] Release a beta version
- [ ] User testing
- [ ] Set-up the servers (kubernetes)
- [ ] https://github.com/hashgraph/hedera-transaction-tool-demo/issues/502
- [ ] Design: How to run the tool locally
```

**Comment by SimiHunjan** [comment]
moved to a different project repo
