### ISSUE TITLE
v0.13.2 Release Checklist

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#499]
### Problem

- [x] Version numbers in the application are updated to `0.13.2`
- [x] The release is tagged in the GitHub repo 
- Includes the CLI tool, the desktop application, the source code (zip/tar.gz)
- [x] The release has completed release notes that cover the changes that were included in the build
- [x] Manual user testing is complete
- [x] The `main` branch is up to date with all related PRs

### Solution

Complete checklist
