### ISSUE TITLE
`0.13.4` Release Checklist

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#518]
### Problem

- [x] Version numbers in the application are updated to `0.13.4`
- [x] The release is tagged in the GitHub repo 
- Includes the CLI tool, the desktop application, the source code (zip/tar.gz)
- [x] The release has completed release notes that cover the changes that were included in the build
- [x] Manual user testing is complete
https://github.com/hashgraph/hedera-transaction-tool-demo/issues/519
- [x] The `main` branch is up to date with all related PRs
- [x] Rebase new versions of the application if a patch was released for a previous version 
- [x] https://github.com/hashgraph/hedera-transaction-tool-demo/issues/517

### Solution

Complete Checklist
