### ISSUE TITLE
0.14.2 Release Checklist

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-transaction-tool-demo#554]
- [x] Version numbers in the application are updated to 0.14.2
- [x]  The release is tagged in the GitHub repo
* Includes the CLI tool, the desktop application, the source code (zip/tar.gz)
- [ ]  The release has completed release notes that cover the changes that were included in the build
- [x]  Manual user testing is complete https://github.com/hashgraph/hedera-transaction-tool-demo/issues/553
- [x]  The main branch is up to date with all related PRs
